FROM python:3.7-slim

ENV PROJECT=aporter
ENV CONTAINER_HOME=/opt
ENV CONTAINER_PROJECT=$CONTAINER_HOME/$PROJECT

ADD . $CONTAINER_PROJECT
WORKDIR $CONTAINER_PROJECT

RUN pip install --no-cache-dir -r $CONTAINER_PROJECT/requirements.txt