version: '3.1'

services:
    nginx:
        container_name: nginx
        volumes:
            - ./:/opt/aporter
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        image: nginx:1.13.7
        ports:
            - 80:80
        networks:
            - my-network
        depends_on:
            - flask
    flask:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: flask
        command: gunicorn app.wsgi --bind 0.0.0.0 --workers 4
        volumes:
            - ./:/opt/aporter
        networks:
            my-network:
                aliases:
                    - flask-app
networks:
    my-network: