version: '3.1'

services:
    nginx:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: nginx
        volumes:
            - ../:/var/www
            - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
            - 443:443
        networks:
            - my-network
        depends_on:
            - flask
    flask:
        build:
            context: ../
            dockerfile: Dockerfile
        container_name: flask
        command: gunicorn app.wsgi --bind 0.0.0.0:443 --workers 4
        volumes:
            - ../:/var/www
        networks:
            my-network:
                aliases:
                    - flask-app
networks:
    my-network: