version: '3.1'

services:
    nginx:
        image: nginx:1.15
        container_name: nginx
        restart: unless-stopped
        volumes:
            - ../:/var/www
            - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        ports:
            - 80:80
            - 443:443
        networks:
            - my-network
        depends_on:
            - flask
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: certbot/certbot
        container_name: certbot
        restart: unless-stopped
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    flask:
        build:
            context: ../
            dockerfile: Dockerfile
        container_name: flask
        command: gunicorn app.wsgi --bind 0.0.0.0:443 --workers 4
        volumes:
            - ../:/var/www
        networks:
            my-network:
                aliases:
                    - flask-app
networks:
    my-network: